### ISSUE TITLE
apiv4: Do not display completed stations for started LABs

### ISSUE THREAD

**Issue by GerneCacher** [mirsch/lab2gpx#142] opened 2024-04-30 07:10 UTC
Hello,
in apiv4 **completed stations** are listed when ‘Include partially completed labs’ is selected.
A switch to deselect completed stations would be nice. Then you will only see open stations for started LABs.
In apiv3 this was the case via ‘Exclude your findings, copy & paste source code of your findings page:’

Thank you

**Comment by mirsch** [comment] 2024-04-30 08:58
duplicate of #140

**Closed by mirsch** 2024-04-30 08:58 UTC
