### ISSUE TITLE
Duplicate name on LAB caches

### ISSUE THREAD

**Issue by nottins** [mirsch/lab2gpx#143] opened 2024-05-01 15:57 UTC
Hello,
I'm writing a bash script to update my finds and found date of Adlabs into GSAK. I've used lab2gpx and I've found 5 lab stages have the same name (GSAK code), but completely different descriptions in the GPX files. Is this a bug with lab2gpx or have Groundspeak got differents AdLab stages with the same name/code?

Please see attached files

Steve
[labs2gpx.txt](https://github.com/mirsch/lab2gpx/files/15178813/labs2gpx.txt)
[labs2gpx.txt](https://github.com/mirsch/lab2gpx/files/15178832/labs2gpx.txt)

**Comment by mirsch** [comment] 2024-05-02 06:03
there is no difference between the 2 files

**Comment by nottins** [comment] 2024-05-02 06:09
My apologies, although the files were in different folders. the uploader used the same file. Please find new files.
[labs2gpx.txt](https://github.com/mirsch/lab2gpx/files/15184368/labs2gpx.txt)
[labs2gpx_1.txt](https://github.com/mirsch/lab2gpx/files/15184369/labs2gpx_1.txt)

**Comment by SamHenkel** [comment] 2024-05-02 07:18
Both AdventureLabs have different core codes. Unfortunately Lab2Gpx does an uppercase formatting by default.
These are the codes: ALDV35 and ALDv35
(https://gsak.net/screenshots/fc2d32daa81e98e0e90326af108673de.png)

NB: The same goes with the prefix LC. That prefix is a valid prefix by Terraching.com for Locationless Caches and is used byGSAK as well. That said;: the prefix should be set to LB by default.

**Comment by nottins** [comment] 2024-05-02 07:36
Thanks for the update, I've updated the GPX files to change the carpool
caches to lower case and loaded them to GSAK.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mirsch** [comment] 2024-05-02 11:44
duplicate of #108

**Comment by mirsch** [comment] 2024-05-02 11:47
the lower-/uppercase thing is discussed in #30

**Comment by mirsch** [comment] 2024-05-02 11:51
> ... Unfortunately Lab2Gpx does an uppercase formatting by default. ...
> ... the prefix should be set to LB by default.

defaults are always very subjective. I try to avoid changing defaults if possible. Maybe we can do some kind of vote for defaults some day ;)

**Closed by mirsch** 2024-05-02 11:51 UTC
