### ISSUE TITLE
Problem with Partially completed Lab sets

### ISSUE THREAD

**Issue by BabsbabyUK** [mirsch/lab2gpx#149] opened 2024-05-07 16:32 UTC
In general, I like the new changes, however, when I download partially completed lab sets, I get **all** the caches in the set, not just the ones I have not found and the ones I have found are not showing as found.   This is a problem for me as I'm preparing a gpx dataset for central London where there are lots of sets of Labs that I have not finished.  Should I be doing the request a different way? 

Thank you

**Comment by balri** [comment] 2024-05-12 22:03
Same. I've been importing all labs into GSAK and then moving the found ones to my Finds DB so that newly found waypoints are cleared out of my default DB. But I've just noticed that found lab waypoints have reappeared in my default DB because they are part of a partially completed lab and are not marked as found even though I've found them

**Comment by mirsch** [comment] 2024-06-06 16:25
duplicate of #144

**Closed by mirsch** 2024-06-06 16:25 UTC
