### ISSUE TITLE
V4 code download all location on a partially completed lab

### ISSUE THREAD

**Issue by jmarlman** [mirsch/lab2gpx#141] opened 2024-04-29 21:55 UTC
Using the new V4 code and specifying Include partially completed labs  and  Include unstarted  I get the unstarted   lab locations for all the partially  completed  locations and the locations that are done and are  completed.  In my case two Labs with 5 location and only one location was not completed all 5 location were downloaded as not done.

**Comment by mirsch** [comment] 2024-04-30 08:58
duplicate of #140

**Closed by mirsch** 2024-04-30 08:58 UTC
