### ISSUE TITLE
Provide a way to download a GPX of your Adventure Location Finds

### ISSUE THREAD

**Issue by crs98** [mirsch/lab2gpx#72] opened 2022-03-11 13:47 UTC
The tool already has a way to drop a list of your past Adventure finds in it, but there is not a way to generate a GPX file of those locations only as far as I can tell.  This would be a helpful tool for those of us who use programs like GSAK to keep track of our past finds as well as our future geocaching activity.

**Comment by NeanderGollum** [comment] 2022-09-04 19:59
Nice idea. I would also like to have it ;-).

**Comment by mirsch** [comment] 2024-04-30 12:41
duplicate of #101

**Closed by mirsch** 2024-04-30 12:41 UTC
