### ISSUE TITLE
Deaktivierte Labs von Events

### ISSUE THREAD

**Issue by Mani1ac** [mirsch/lab2gpx#120] opened 2023-05-14 14:13 UTC
Hallo,
ich habe versucht meine Funde zu importieren aber alte LabAdventures von Megaevents werden nicht aufgeführt. Wie bekomme  ich die in meine Statistik?

Gretes

Mani.ac

**Comment by PlasmaWave** [comment] 2023-05-16 06:03
All completed Lab stages are shown in your geocaching.com profile. I copied my list into Excel, then extracted Lab names, completeion dates, co-ords, etc, to a text file then imported that into GSAK. Not super quick, but is a one-off task to have all your completed Lab stages in one place.

**Comment by mirsch** [comment] 2024-04-30 12:54
duplicate of #15

**Closed by mirsch** 2024-04-30 12:54 UTC
